name: keystone
version: 0
summary: OpenStack Identity Service (keystone)
description: OpenStack Identity Service (keystone)
confinement: strict
grade: devel

apps:
  apache:
    command: bin/apache-wrapper start
    stop-command: bin/apache-wrapper stop
    daemon: simple
    plugs:
      - network
  uwsgi:
    command: bin/apache-uwsgi
    daemon: simple
    plugs:
      - network
  manage:
    command: keystone-manage
    plugs:
      - network

parts:
  apache:
    plugin: autotools
    source: http://mirrors.hostingromania.ro/apache.org/httpd/httpd-2.4.23.tar.gz
#    configflags: [--enable-pie, --enable-mpms-shared=all, --enable-mods-shared="all cgi ident authnz_fcgi", --enable-mods-static="unixd logio watchdog version"]
#    configflags: [--enable-pie, --enable-mpms-shared=all, --enable-mods-shared=all, --enable-mods-static="unixd logio watchdog version", --enable-proxy, --enable-proxy-connect, --enable-proxy-http, --enable-rewrite, --enable-ssl]
    configflags: ['--enable-mpms-shared=all', '--enable-pie', '--enable-proxy', '--enable-proxy-connect', '--enable-proxy-http', '--enable-rewrite', '--enable-ssl']
    stage-packages:
      # Apache dependencies
      - libapr1
      - libaprutil1
      - libpcre3
    build-packages:
      # Apache dependencies
      - libapr1-dev
      - libaprutil1-dev
      - libpcre3-dev
  keystone:
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/keystone/keystone-stable-mitaka.tar.gz
    python-packages:
        - pymysql
        - uwsgi
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/mitaka/upper-constraints.txt
    build-packages:
        - libffi-dev
        - libssl-dev
        - pkg-config
    stage-packages:
        - apache2
        - libapache2-mod-proxy-uwsgi
  config:
    after:
      - keystone
    plugin: dump
    source: conf
