name: keystone
version: 0
summary: OpenStack Identity Service (keystone)
description: OpenStack Identity Service (keystone)
confinement: strict

apps:
  keystone:
    command: bin/run.sh keystone-all
    daemon: simple
    plugs:
      - network-bind
      - network
  keystone-manage:
    command: bin/run.sh keystone-manage
    plugs:
      - network
      - network-bind

parts:
  keystone:
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/keystone/keystone-stable-mitaka.tar.gz
    python-packages:
        - pymysql
        - uwsgi
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/mitaka/upper-constraints.txt
    build-packages:
        - libssl-dev
        - libffi-dev
        - pkg-config
  config:
    plugin: copy
    files:
      ../../../parts/keystone/src/etc/*: etc/keystone/
      etc/keystone.conf: etc/keystone/keystone.conf
      templates/*: templates/
      bin/run.sh: bin/run.sh
